# Generated by Django 4.0.5 on 2022-06-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immfly_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='immfly_api.channel'),
        ),
    ]
